### PR TITLE
Add Prism Launcher detection

### PR DESCRIPTION
**Pull request by pandaninjas**
Same as PolyMC but uses a different directory

### CODE REVIEW

**Comment by KTibow** [comment]
code quality
don't get the home/data path twice
extract out the thing that retrieves data + instances for each path

**Comment by KTibow** [comment]
image

**Comment by KTibow** [comment]
you need an empty catch block

**Comment by KTibow** [comment]
tbh ill probably just rewrite this myself, nice work tho

**Comment by KTibow** [comment]
should i make a new release?

**Comment by pandaninjas** [comment]
> should i make a new release?

idk, do what you want to do

**Pull request closed without merging**
